<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

	<xsl:template name="license">
Online License Agreement and Terms of Use

This is a legal agreement between you (the &quot;USER&quot;), and Helmholtz Zentrum Muenchen - Deutsches Forschungszentrum fuer Gesundheit und Umwelt (&quot;HMGU&quot;), covering your use of the Online Chemical Database &amp; Modeling Environment and the accompanying Software (&quot;OCHEM&quot;). Be sure to read the following agreement before using OCHEM.

HMGU is willing to license the use of OCHEM upon the condition that you accept all of the terms contained in this License Agreement and any supplementary license terms included herewith ("Agreement").

By using OCHEM, you agree to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement you are not authorized to use OCHEM.

AS THE USER YOU AGREE TO ACCEPT THE FOLLOWING TERMS AND CONDITIONS:

Software License Agreement

1. OCHEM Software License to the USER

1.1 HMGU grants to the USER a non-exclusive, non-transferable license to use OCHEM solely for non-commercial purposes. No express or implied license is granted to USER for any other purpose. The USER shall not copy, modify, decompile, disassemble, decrypt, extract, or otherwise reverse engineer OCHEM.

1.2 &quot;DATA&quot; comprises any information about the physico-chemical and biological properties of chemical structures, experimental conditions, chemical identifiers, names and structures themselves that are submitted by users to OCHEM. The USER is granted a Creative Commons CC-BY (version 4.0) license to DATA submitted and made available by other users under this Agreement.

1.3 &quot;MODELS&quot; are implemented mathematical functions of OCHEM that use DATA. MODELS generated through OCHEM become a part of OCHEM Software. The USER is granted a Creative Commons CC-BY-NC (version 4.0) license to use these MODELS.


2. USER License on DATA and MODELS

2.1 The USER grants to all other users of OCHEM a right to use all DATA submitted by USER to OCHEM according to the Creative Commons CC-BY (version 4.0) license. The USER warrants, that to the best of his knowledge the DATA submitted by him to OCHEM does not infringe any intellectual property rights of a third party.

2.2 The USER grants to all other users of OCHEM a Creative Commons CC-BY-NC (version 4.0) license to use MODELS generated by USER through OCHEM.

2.3 The USER grants to HMGU a world-wide, non-exclusive, transferable and sub-licensable right to use MODELS generated by USER for research, teaching and any other (including commercial) purposes.


3. Confidentiality of DATA and MODELS

3.1 HMGU will collect DATA and other information supplied by USER to OCHEM for computational purposes.

3.2 By submitting DATA to OCHEM and by generating MODELS through the use of OCHEM, the USER makes such DATA and MODELS available to all other users of OCHEM according to Section 2.

3.3 HMGU offers a password protection feature that provides temporary confidentiality of DATA or MODELS of the USER, If the USER opts for such password protection for specific DATA or MODELS, HMGU will disable access of the other users of OCHEM to such DATA or MODELS for a period of six months following the submission of such DATA or MODELS (this period can be prolonged for an additional six months by e-mail to "info AT ochem.eu") or until earlier released by the USER. After the expiry of such a confidentiality period such DATA or MODELS may be deleted according to the procedure set out in Section 4.2 or publicly released at the discretion of HMGU. 

3.4 The USER agrees that, if he registers on the OCHEM website and therefore provides personal Information as defined in the Privacy Policy below, he can be cited with his full and login name in conjunction with all MODELS and DATA he stores and publishes on OCHEM.


4. Limited Warranty.

4.1 OCHEM IS LICENSED "AS IS." HMGU disclaims all warranties concerning software, information, data, structures and models express or implied, including, but not limited to any implied warranties of merchantability, fitness for a particular purpose or non-infringement of any intellectual property rights.

4.2. The DATA provided on the OCHEM website may contain inaccuracies and typographical errors. HMGU does not warrant the accuracy or completeness of the DATA or the reliability of any advice, opinion, statement or other information displayed or distributed through OCHEM. The USER acknowledges that any reliance on any DATA, opinion, advice, statement, memorandum, materials or information shall be at his sole risk. HMGU reserves the right, to its sole discretion, to correct any errors or omissions or, in exceptional cases, to delete any DATA or MODELS in any portion of OCHEM, provided such DATA or MODELS were identified to be erroneous, false (e.g., calculated rather than experimental values) incomplete or spurious by HMGU or by other USERs who are authorized to do it (&quot;MODERATORs&quot;). In most cases HMGU/MODERATORs will try to contact the USER before deleting the DATA, as well as notifying the USER via email about the reason of such action. Before permanent removal deleted DATA will be placed in a &quot;Trash&quot; folder on OCHEM and can be restored from it by the USER after correction of errors.  HMGU may make any other changes to OCHEM and the Software, Data, materials and products, programs or services described or provided on OCHEM at any time without notice.

4.3 HMGU does not warrant the on-line availability of OCHEM and the DATA stored therein. HMGU may terminate OCHEM at its sole discretion at any time without notice according to Section 6.2.


5. Limitation of Liability.
5.1 In no event will HMGU be liable for any lost revenue, profit or data or for special, indirect, consequential, incidental or punitive damages however caused and regardless of the theory of liability arising out of the use or inability to use OCHEM, the DATA or software therein, even if HMGU has been advised of the possibility of such damages. The foregoing limitations shall apply even if the above stated warranty fails of its essential purpose.

5.2 Section 4.1, 4.2 and 5.1 apply accordingly to the USER, which provides DATA to OCHEM, in regard to the DATA provided.


6. Termination.

6.1 This License is effective until being terminated. This License will terminate immediately without notice, if USER fails to comply with any provision of this License. Upon termination, the account of the USER can be blocked and/or be removed.

6.2 HMGU reserves the right, to its sole discretion to terminate OCHEM at any time at its discretion. With termination of OCHEM this License will terminate immediately without notice from HMGU.

6.3. The Provisions of Section 3, 4 and 5 will survive any termination of this License Agreement.


7. Governing Law.

This Agreement is made under, shall be governed by and construed in accordance with the laws of Germany, excluding its choice of law provisions.


8. Severability.

Should any provision of this Agreement be invalid or unenforceable or should the Agreement contain an omission, the remaining provisions shall be valid. However, if in HMGU’s opinion deletion of any provisions of this Agreement by operation of this paragraph unreasonably compromises the rights or liabilities of HMGU, HMGU reserves the right to terminate this Agreement.

By clicking the acceptance button and submitting DATA and MODELS to OCHEM, I acknowledge that I have read and fully understood the foregoing Agreement and I agree to abide by its terms and conditions.

Right to Information
You have at all times the right to information regarding your stored Personal Information, the origin of the information and its acceptor as well as to the purpose of the storage of your Personal Information.
If you have any comments or questions regarding this Online Privacy Policy or your stored Personal Information, please contact &quot;info AT ochem.eu&quot;
</xsl:template>
	
</xsl:stylesheet>
