//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.01 at 11:00:06 AM CEST 
//


/* Copyright (C) 2022 BIGCHEM GmbH <info@bigchem.de>
 *
 * Contact: info@bigchem.de
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * as published by the Free Software Foundation; either version 3.0
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Affero GNU General Public License for more details.
 *
 * You should have received a copy of the Affero GNU Lesser General Public License
 * along with this program; If not, see <https://www.gnu.org/licenses/>. 
 */

package qspr.util.ncbi.eSearch;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the qspr.util.ncbiUtil package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: qspr.util.ncbiUtil
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Translation }
     * 
     */
    public Translation createTranslation() {
        return new Translation();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link TermSet }
     * 
     */
    public TermSet createTermSet() {
        return new TermSet();
    }

    /**
     * Create an instance of {@link OP }
     * 
     */
    public OP createOP() {
        return new OP();
    }

    /**
     * Create an instance of {@link RetStart }
     * 
     */
    public RetStart createRetStart() {
        return new RetStart();
    }

    /**
     * Create an instance of {@link QueryTranslation }
     * 
     */
    public QueryTranslation createQueryTranslation() {
        return new QueryTranslation();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link Count }
     * 
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link OutputMessage }
     * 
     */
    public OutputMessage createOutputMessage() {
        return new OutputMessage();
    }

    /**
     * Create an instance of {@link ESearchResult }
     * 
     */
    public ESearchResult createESearchResult() {
        return new ESearchResult();
    }

    /**
     * Create an instance of {@link ErrorList }
     * 
     */
    public ErrorList createErrorList() {
        return new ErrorList();
    }

    /**
     * Create an instance of {@link WebEnv }
     * 
     */
    public WebEnv createWebEnv() {
        return new WebEnv();
    }

    /**
     * Create an instance of {@link Explode }
     * 
     */
    public Explode createExplode() {
        return new Explode();
    }

    /**
     * Create an instance of {@link WarningList }
     * 
     */
    public WarningList createWarningList() {
        return new WarningList();
    }

    /**
     * Create an instance of {@link QuotedPhraseNotFound }
     * 
     */
    public QuotedPhraseNotFound createQuotedPhraseNotFound() {
        return new QuotedPhraseNotFound();
    }

    /**
     * Create an instance of {@link PhraseIgnored }
     * 
     */
    public PhraseIgnored createPhraseIgnored() {
        return new PhraseIgnored();
    }

    /**
     * Create an instance of {@link TranslationSet }
     * 
     */
    public TranslationSet createTranslationSet() {
        return new TranslationSet();
    }

    /**
     * Create an instance of {@link QueryKey }
     * 
     */
    public QueryKey createQueryKey() {
        return new QueryKey();
    }

    /**
     * Create an instance of {@link TranslationStack }
     * 
     */
    public TranslationStack createTranslationStack() {
        return new TranslationStack();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link ERROR }
     * 
     */
    public ERROR createERROR() {
        return new ERROR();
    }

    /**
     * Create an instance of {@link IdList }
     * 
     */
    public IdList createIdList() {
        return new IdList();
    }

    /**
     * Create an instance of {@link FieldNotFound }
     * 
     */
    public FieldNotFound createFieldNotFound() {
        return new FieldNotFound();
    }

    /**
     * Create an instance of {@link RetMax }
     * 
     */
    public RetMax createRetMax() {
        return new RetMax();
    }

    /**
     * Create an instance of {@link PhraseNotFound }
     * 
     */
    public PhraseNotFound createPhraseNotFound() {
        return new PhraseNotFound();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

}
